# Generated by Django 5.1.7 on 2025-05-16 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_created_comment',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 6, 27, 5, 610592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 6, 27, 5, 610253, tzinfo=datetime.timezone.utc)),
        ),
    ]
