# Generated by Django 5.1.7 on 2025-05-30 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_comment_data_created_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_created_comment',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 8, 20, 26, 590326, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 8, 20, 26, 589969, tzinfo=datetime.timezone.utc)),
        ),
    ]
